//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalesGenerator.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TalesGenerator.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #агент.
        /// </summary>
        public static string AgentLabel {
            get {
                return ResourceManager.GetString("AgentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string AgentResourceLabel {
            get {
                return ResourceManager.GetString("AgentResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ:.
        /// </summary>
        public static string AnswerLabel {
            get {
                return ResourceManager.GetString("AnswerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string AnswerNo {
            get {
                return ResourceManager.GetString("AnswerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string AnswerYes {
            get {
                return ResourceManager.GetString("AnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TalesGenerator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименовать вершину.
        /// </summary>
        public static string ChangeNodeTextLabel {
            get {
                return ResourceManager.GetString("ChangeNodeTextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть проект.
        /// </summary>
        public static string CloseProject {
            get {
                return ResourceManager.GetString("CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать консультацию.
        /// </summary>
        public static string ConsultStartLabel {
            get {
                return ResourceManager.GetString("ConsultStartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Консультация.
        /// </summary>
        public static string ConsultWindowCaption {
            get {
                return ResourceManager.GetString("ConsultWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую вершину.
        /// </summary>
        public static string CreateNewNodeLabel {
            get {
                return ResourceManager.GetString("CreateNewNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить дугу.
        /// </summary>
        public static string DeleteLinkLabel {
            get {
                return ResourceManager.GetString("DeleteLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить вершину.
        /// </summary>
        public static string DeleteNodeLabel {
            get {
                return ResourceManager.GetString("DeleteNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потомки.
        /// </summary>
        public static string DescendantsLabel {
            get {
                return ResourceManager.GetString("DescendantsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты сети.
        /// </summary>
        public static string DispatcherLabel {
            get {
                return ResourceManager.GetString("DispatcherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование.
        /// </summary>
        public static string EditLabel {
            get {
                return ResourceManager.GetString("EditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите вопрос:.
        /// </summary>
        public static string EnterQuestionLabel {
            get {
                return ResourceManager.GetString("EnterQuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorMsgCaption {
            get {
                return ResourceManager.GetString("ErrorMsgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string ExitLabel {
            get {
                return ResourceManager.GetString("ExitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт.
        /// </summary>
        public static string ExportProject {
            get {
                return ResourceManager.GetString("ExportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #следовать.
        /// </summary>
        public static string FollowLabel {
            get {
                return ResourceManager.GetString("FollowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string FollowResourceLabel {
            get {
                return ResourceManager.GetString("FollowResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #цель.
        /// </summary>
        public static string GoalLabel {
            get {
                return ResourceManager.GetString("GoalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal.
        /// </summary>
        public static string GoalResourceLabel {
            get {
                return ResourceManager.GetString("GoalResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экземпляры.
        /// </summary>
        public static string InstancesLabel {
            get {
                return ResourceManager.GetString("InstancesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #is_a.
        /// </summary>
        public static string IsALabel {
            get {
                return ResourceManager.GetString("IsALabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsA.
        /// </summary>
        public static string IsAResourceLabel {
            get {
                return ResourceManager.GetString("IsAResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #is_instance.
        /// </summary>
        public static string IsInstanceLabel {
            get {
                return ResourceManager.GetString("IsInstanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsInstance.
        /// </summary>
        public static string IsInstanceResourceLabel {
            get {
                return ResourceManager.GetString("IsInstanceResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дуги.
        /// </summary>
        public static string LinksLabel {
            get {
                return ResourceManager.GetString("LinksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип дуги.
        /// </summary>
        public static string LinkTypeLabel {
            get {
                return ResourceManager.GetString("LinkTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #локатив.
        /// </summary>
        public static string LocativeLabel {
            get {
                return ResourceManager.GetString("LocativeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locative.
        /// </summary>
        public static string LocativeResourceLabel {
            get {
                return ResourceManager.GetString("LocativeResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый проект.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вершины.
        /// </summary>
        public static string NodesLabel {
            get {
                return ResourceManager.GetString("NodesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ДиспетчерОбъектов.
        /// </summary>
        public static string ObjectDispatcher {
            get {
                return ResourceManager.GetString("ObjectDispatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть проект.
        /// </summary>
        public static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #part_of.
        /// </summary>
        public static string PartOfLabel {
            get {
                return ResourceManager.GetString("PartOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartOf.
        /// </summary>
        public static string PartOfResourceLabell {
            get {
                return ResourceManager.GetString("PartOfResourceLabell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #реципиент.
        /// </summary>
        public static string RecipientLabel {
            get {
                return ResourceManager.GetString("RecipientLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string RecipientResourceLabel {
            get {
                return ResourceManager.GetString("RecipientResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспортировать в PDF.
        /// </summary>
        public static string SaveAsPdf {
            get {
                return ResourceManager.GetString("SaveAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить как.
        /// </summary>
        public static string SaveAsProject {
            get {
                return ResourceManager.GetString("SaveAsProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспортировать в SVG.
        /// </summary>
        public static string SaveAsSvg {
            get {
                return ResourceManager.GetString("SaveAsSvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий проект содержит изменения. Желаете сохранить его перед закрытием?.
        /// </summary>
        public static string SaveWarning {
            get {
                return ResourceManager.GetString("SaveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск.
        /// </summary>
        public static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите новое значение:.
        /// </summary>
        public static string StringEditWndEnterLabel {
            get {
                return ResourceManager.GetString("StringEditWndEnterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string TemlateResourceLabel {
            get {
                return ResourceManager.GetString("TemlateResourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #шаблон.
        /// </summary>
        public static string TemplateLabel {
            get {
                return ResourceManager.GetString("TemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Связи.
        /// </summary>
        public static string TreeLinks {
            get {
                return ResourceManager.GetString("TreeLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вершины.
        /// </summary>
        public static string TreeNodes {
            get {
                return ResourceManager.GetString("TreeNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объекты сети.
        /// </summary>
        public static string TreeObjects {
            get {
                return ResourceManager.GetString("TreeObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Неименованная вершина&gt;.
        /// </summary>
        public static string UnnamedLinkLabel {
            get {
                return ResourceManager.GetString("UnnamedLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличить.
        /// </summary>
        public static string ZoomInLabel {
            get {
                return ResourceManager.GetString("ZoomInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уменьшить.
        /// </summary>
        public static string ZoomOutLabel {
            get {
                return ResourceManager.GetString("ZoomOutLabel", resourceCulture);
            }
        }
    }
}
